repos:
  - repo: https://github.com/batmac/pre-commit-zig
    rev: v0.3.0
    hooks:
      - id: zig-fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(patches/.*\.patch|oss-fuzz/corpus/)
      - id: end-of-file-fixer
        exclude: ^oss-fuzz/corpus/
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: zon2nix
        name: zon2nix
        entry: bash scripts/update_zon_files.sh
        language: system
        files: ^build\.zig\.zon$
        pass_filenames: false
