# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  fetchgit,
  fetchurl,
  fetchzip,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
  # Accepted and ignored. Expressions from zon2nix before 0.8 built the
  # packages with `linkFarm`, and some callers override it with a version that
  # copies, to work around Zig mishandling symlinked package directories
  # (https://codeberg.org/ziglang/zig/issues/32121). The packages are real
  # directories now, so the override is not needed, and is taken here only so
  # that passing it is not an error.
  linkFarm ? null,
}:
let
  # A git repository, checked out the way Zig reads it: every file as
  # committed. An ordinary checkout applies the repository's `.gitattributes`,
  # which can rewrite a file's line endings or run it through a filter, and
  # the package would then no longer match its hash. Pointing git at its
  # built-in empty tree for attributes turns them all off, and `core.autocrlf`
  # is turned off too, since it converts line endings even without them.
  # zon2nix computes the hash with exactly these settings.
  fetchZigGit =
    args:
    fetchgit (
      args
      // {
        fetchSubmodules = false;
        preFetch = ''
          export GIT_ATTR_SOURCE=4b825dc642cb6eb9a060e54bf8d69288fbee4904
          export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.autocrlf GIT_CONFIG_VALUE_0=false
        '';
      }
    );

  # Every package, by the hash Zig knows it by, as Nix fetches it.
  packages = {
    "N-V-__8AAI8Hdw49zvJpQMT6mP3lUI2BU88KafEc3BkYlcu6" = fetchZigGit {
      name = "boringssl";
      url = "https://github.com/google/boringssl";
      rev = "dd73e69a4e86fa178a4d19033c691e9b42cc1088";
      hash = "sha256-cSwDjwSPP13GB4as9Nwm8iQTN/K2ZP5T9wVHWTzYQA4=";
    };
    "N-V-__8AAEaRCwCsYb_rSsH72Pb6DNFQLSjdRzTFOVsJWcoB" = fetchZigGit {
      name = "libdeflate";
      url = "https://github.com/ebiggers/libdeflate";
      rev = "92e6a0db9fa848d742f9eb286c92afc60f2c3dda";
      hash = "sha256-QVF2XL8Qu3mTszKKtx+8BExkTGkpMANXjkAe3XXPUJQ=";
    };
    "libxev-0.0.0-86vtcwIRFADbH4hk-EjROXxlrKIRPQdA41XiTSytYO-F" = fetchZigGit {
      name = "libxev";
      url = "https://github.com/mitchellh/libxev";
      rev = "9ce8e8e6ff89e583258a7f8e7adeeeaeae8611bf";
      hash = "sha256-fOU1oxIxfoEgoLuWz7fVX6M+zmqpo7gqZObWiH/aDE0=";
    };
    "N-V-__8AABFJVQBMmGjr7hbydaG9qS3FWrGChwmOj7c-A6Xy" = fetchZigGit {
      name = "lshpack";
      url = "https://github.com/litespeedtech/ls-hpack";
      rev = "38ceca78054d4175ba3f6411b1b83ac5c485e542";
      hash = "sha256-JeXjNds4Gc+dkieA0TQmbhoPvozAx/23FO8HgjQu5wE=";
    };
    "N-V-__8AANUVVwDVcoOf9vCuxr9NUBhMvdV-XuREQFIxja8H" = fetchZigGit {
      name = "lsqpack";
      url = "https://github.com/litespeedtech/ls-qpack";
      rev = "91567706c41c0d97ab8dc576873ecd472d7869fa";
      hash = "sha256-kbwtvlEmWBA+qUUwYhpZuh5rvNxBum30d6RQDbAF5AM=";
    };
    "N-V-__8AABlSZwC2bZHS0kM4Fi6Cz3MPxNN3TFeim4QI6R9A" = fetchZigGit {
      name = "lsquic";
      url = "https://github.com/litespeedtech/lsquic";
      rev = "d5929af7cec6fd74f1cfea2cb1c07c27ce9102b1";
      hash = "sha256-kb47Ibl3S9sBsNuhyaYhh1ix9Jb60FOMkCGVD6FIizU=";
    };
    "N-V-__8AAJ2cNgAgfBtAw33Bxfu1IWISDeKKSr3DAqoAysIJ" = fetchzip {
      name = "zlib";
      url = "https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz";
      hash = "sha256-tKLefmGqB2HVUMILJ7Gqa0v9GH7fqv64d5S5kK1tcYU=";
    };
    "zslay-0.2.1-OB-IfBl0AQCHCIVUH0AbAjErcCG_LNkaLp8Gz1BUXnoy" = fetchzip {
      name = "zslay";
      url = "https://github.com/farbenbuilds/zslay/archive/refs/tags/v0.2.1.tar.gz";
      hash = "sha256-ogoYdgzWM0nD/Q8rUE37UzH1tXCPEWHs7Fm60nqbU54=";
    };
  };

  # The packages whose own manifest declares a dependency by `.path`. Zig
  # 0.16.0 cannot build these through `zig build --system`: it spins in
  # userspace forever, because a `.path` dependency's hash is computed against
  # the system package directory during the fetch and against the real global
  # cache afterwards, and in that mode the two disagree. A package that wants
  # `--system` copies each of these into its build root and passes `--fork=`;
  # see the README.
  pathDependencyPackages = [
  ];
in
# One directory holding every package the way Zig unpacks it -- filtered by
# its manifest's `.paths` and checked against its hash -- which is what
# `zig build --system` wants.
#
# They have to be real directories holding real files, not links into each
# package's own store path. Zig runs a dependency's build steps from inside
# it and counts its way back out through `..`, which lands in the wrong place
# when the directory is a symlink; and `installHeadersDirectory` copies only
# what the directory walk calls a file, so symlinked headers are skipped
# without a word. Building them all in one derivation gives real files from
# the start, without a second copy of everything.
runCommandLocal name
  {
    nativeBuildInputs = [ zig_0_16 ];
    passthru = { inherit pathDependencyPackages; };
  }
  ''
    mkdir "$out"

    # Each package gets a directory of its own to work in, since `zig fetch`
    # leaves what it unpacked in `zig-pkg/` under the directory it ran in.
    unpack() {
      local work="$TMPDIR/work/$1"
      mkdir -p "$work/src" "$work/cache/tmp"
      # workaround https://codeberg.org/ziglang/zig/issues/31866
      # https://github.com/Cloudef/zig2nix/issues/54
      touch "$work/src/build.zig"
      # `zig fetch` recompresses every package into `p/` at gzip level 9 for
      # its own cache, which is nearly all of its time and of no use here.
      # With `p` a file rather than a directory that step fails at once --
      # Zig warns, and carries on -- and the package is left in `zig-pkg/`.
      touch "$work/cache/p"

      local hash
      if ! hash="$(cd "$work/src" && zig fetch --global-cache-dir "$work/cache" "$2" 2>"$work/log")"; then
        cat "$work/log" >&2
        return 1
      fi
      if [ "$hash" != "$1" ]; then
        echo "$2 is $hash to Zig, not $1" >&2
        return 1
      fi
      mv "$work/src/zig-pkg/$1" "$out/$1"
      rm -rf "$work"
    }
    export -f unpack

    # Several at a time: `zig fetch` spends most of a package on one core.
    # `-r` because otherwise xargs runs `unpack` once, with no arguments, when
    # there are no packages at all, and the build fails.
    cores="''${NIX_BUILD_CORES:-0}"
    if [ "$cores" -le 0 ]; then cores="$(nproc)"; fi
    xargs -r -P "$cores" -n 2 bash -c 'unpack "$@"' unpack <<'EOF'
    ${lib.concatStrings (lib.mapAttrsToList (hash: src: "${hash} ${src}\n") packages)}
    EOF
  ''
