# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchzip,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig_0_16,
  zstd,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig_0_16 ];
      }
      ''
        # workaround https://codeberg.org/ziglang/zig/issues/31866
        # https://github.com/Cloudef/zig2nix/issues/54
        touch "$TMPDIR/build.zig"
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash.tar.gz" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      artifact =
        if unpack then
          fetchzip {
            inherit url hash;
            nativeBuildInputs = [ zstd ];
          }
        else
          fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      unpack,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash unpack;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash unpack;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "N-V-__8AAOwHdQ5FYM2zAEn_gDBFEdKKYEl0JirYRSR7y_Sk";
    path = fetchZigArtifact {
      name = "boringssl";
      url = "git+https://github.com/google/boringssl#5fbad2285b096858fc9afa3e4c949fde39452070";
      hash = "sha256-4vt/yjZwgtEVpgZ9CUGjJqKz0HcbOvuozPtmBeKcjlM=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAEaRCwCsYb_rSsH72Pb6DNFQLSjdRzTFOVsJWcoB";
    path = fetchZigArtifact {
      name = "libdeflate";
      url = "git+https://github.com/ebiggers/libdeflate#92e6a0db9fa848d742f9eb286c92afc60f2c3dda";
      hash = "sha256-QVF2XL8Qu3mTszKKtx+8BExkTGkpMANXjkAe3XXPUJQ=";
      unpack = true;
    };
  }
  {
    name = "libxev-0.0.0-86vtcwIRFADbH4hk-EjROXxlrKIRPQdA41XiTSytYO-F";
    path = fetchZigArtifact {
      name = "libxev";
      url = "git+https://github.com/mitchellh/libxev#9ce8e8e6ff89e583258a7f8e7adeeeaeae8611bf";
      hash = "sha256-fOU1oxIxfoEgoLuWz7fVX6M+zmqpo7gqZObWiH/aDE0=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AABFJVQBMmGjr7hbydaG9qS3FWrGChwmOj7c-A6Xy";
    path = fetchZigArtifact {
      name = "lshpack";
      url = "git+https://github.com/litespeedtech/ls-hpack#38ceca78054d4175ba3f6411b1b83ac5c485e542";
      hash = "sha256-JeXjNds4Gc+dkieA0TQmbhoPvozAx/23FO8HgjQu5wE=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AANUVVwDVcoOf9vCuxr9NUBhMvdV-XuREQFIxja8H";
    path = fetchZigArtifact {
      name = "lsqpack";
      url = "git+https://github.com/litespeedtech/ls-qpack#91567706c41c0d97ab8dc576873ecd472d7869fa";
      hash = "sha256-kbwtvlEmWBA+qUUwYhpZuh5rvNxBum30d6RQDbAF5AM=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AABlSZwC2bZHS0kM4Fi6Cz3MPxNN3TFeim4QI6R9A";
    path = fetchZigArtifact {
      name = "lsquic";
      url = "git+https://github.com/litespeedtech/lsquic#d5929af7cec6fd74f1cfea2cb1c07c27ce9102b1";
      hash = "sha256-kb47Ibl3S9sBsNuhyaYhh1ix9Jb60FOMkCGVD6FIizU=";
      unpack = true;
    };
  }
  {
    name = "N-V-__8AAJ2cNgAgfBtAw33Bxfu1IWISDeKKSr3DAqoAysIJ";
    path = fetchZigArtifact {
      name = "zlib";
      url = "https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz";
      hash = "sha256-uzKaCizQJ00FUZ1hxmfAYuBpkNcuEl7i36jeZPARnRY=";
      unpack = false;
    };
  }
  {
    name = "zslay-0.2.1-OB-IfBl0AQCHCIVUH0AbAjErcCG_LNkaLp8Gz1BUXnoy";
    path = fetchZigArtifact {
      name = "zslay";
      url = "https://github.com/farbenbuilds/zslay/archive/refs/tags/v0.2.1.tar.gz";
      hash = "sha256-ogoYdgzWM0nD/Q8rUE37UzH1tXCPEWHs7Fm60nqbU54=";
      unpack = true;
    };
  }
]
