//! Canonical HTTP status codes and their status lines.

/// Final-response status codes covered by the canonical status lines.
pub const StatusCode = enum(u16) {
    ok = 200,
    created = 201,
    accepted = 202,
    no_content = 204,
    partial_content = 206,
    moved_permanently = 301,
    found = 302,
    see_other = 303,
    not_modified = 304,
    temporary_redirect = 307,
    permanent_redirect = 308,
    bad_request = 400,
    unauthorized = 401,
    forbidden = 403,
    not_found = 404,
    method_not_allowed = 405,
    not_acceptable = 406,
    conflict = 409,
    gone = 410,
    length_required = 411,
    content_too_large = 413,
    unsupported_media_type = 415,
    unprocessable_entity = 422,
    too_many_requests = 429,
    internal_server_error = 500,
    not_implemented = 501,
    bad_gateway = 502,
    service_unavailable = 503,
    gateway_timeout = 504,
};

/// Returns the canonical status line, for example "404 Not Found".
pub fn line(code: StatusCode) []const u8 {
    return switch (code) {
        .ok => "200 OK",
        .created => "201 Created",
        .accepted => "202 Accepted",
        .no_content => "204 No Content",
        .partial_content => "206 Partial Content",
        .moved_permanently => "301 Moved Permanently",
        .found => "302 Found",
        .see_other => "303 See Other",
        .not_modified => "304 Not Modified",
        .temporary_redirect => "307 Temporary Redirect",
        .permanent_redirect => "308 Permanent Redirect",
        .bad_request => "400 Bad Request",
        .unauthorized => "401 Unauthorized",
        .forbidden => "403 Forbidden",
        .not_found => "404 Not Found",
        .method_not_allowed => "405 Method Not Allowed",
        .not_acceptable => "406 Not Acceptable",
        .conflict => "409 Conflict",
        .gone => "410 Gone",
        .length_required => "411 Length Required",
        .content_too_large => "413 Content Too Large",
        .unsupported_media_type => "415 Unsupported Media Type",
        .unprocessable_entity => "422 Unprocessable Entity",
        .too_many_requests => "429 Too Many Requests",
        .internal_server_error => "500 Internal Server Error",
        .not_implemented => "501 Not Implemented",
        .bad_gateway => "502 Bad Gateway",
        .service_unavailable => "503 Service Unavailable",
        .gateway_timeout => "504 Gateway Timeout",
    };
}
