const std = @import("std");

/// Writes the repository-root `compile_flags.txt` that clangd uses to analyze
/// the C shim and the C ABI tests.
///
/// The C dependency headers live in Zig's package cache, so the include roots
/// are resolved from the pinned dependencies at configure time instead of being
/// committed. The generated file is listed in `.gitignore`; run
/// `zig build clangd` after the first fetch or whenever a dependency is bumped.
pub fn inject(b: *std.Build) *std.Build.Step {
    var contents: std.ArrayList(u8) = .empty;
    contents.appendSlice(
        b.allocator,
        "# Generated by `zig build clangd`; do not edit or commit.\n",
    ) catch @panic("out of memory");

    // Do not add lsqpack/lshpack roots here: their lsxpack_header.h layout
    // differs from the copy the build uses. No language-standard flag is added
    // either: the file is shared by C and C++ sources, and clangd resolves the
    // toolchain's own C++ standard library.
    const include_roots = [_]std.Build.LazyPath{
        b.path("include"),
        b.dependency("boringssl", .{}).path("include"),
        b.dependency("lsquic", .{}).path("include"),
        b.dependency("libdeflate", .{}).path(""),
        b.dependency("zlib", .{}).path(""),
    };
    for (include_roots) |root| {
        contents.appendSlice(
            b.allocator,
            b.fmt("-I{s}\n", .{root.getPath(b)}),
        ) catch @panic("out of memory");
    }

    const update = b.addUpdateSourceFiles();
    update.addBytesToSource(contents.items, "compile_flags.txt");
    return &update.step;
}
