name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  fmt:
    name: Check Zig Formatting
    runs-on: ubuntu-24.04
    environment: Linting
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run Zig fmt
        run: nix develop "path:." -c zig fmt --check build.zig build.zig.zon src examples tests fuzz

      - name: Check repository conventions
        run: nix develop "path:." -c sh scripts/check_conventions.sh
